### ISSUE TITLE
Suggestion: Share milestones in the TODO / list some of the next steps (or those after that)

### ISSUE THREAD

**Issue by DivineDominion** [FluxHarmonic/flux-compose#6]
This is just a suggestion that could be useful if you want to invite contributors from your stream early: apart from getting the project setting working, maybe add to the `TODO.org` some rough sketches of upcoming milestones that clarify what's going to happen.

For example, you talked about unit tests in C and Guile on 2021-12-30. Someone else could help figure out how to set this up so you can `make test`, for example.

Could also be useful to plan ahead parts  of the "domain model", for the lack of better terms. What's going to be a first slice of functionality? Could someone interested in doing a fun side project help with anything? Implement a file loader? Or a data structure to facilitate video cutting? Stuff like that. 

------

I'm not implying that this is trivial or that coordinating collaborations would be. It's fun to follow along, and I can see myself hacking along, but there's no productive hacking to do that I could turn into a PR because I don't know where this is going :)

**Comment by daviwil** [comment]
Good idea!  I added a basic set of milestones here: https://github.com/FluxHarmonic/flux-compose/commit/6327da52a9580a8b06b3f83bd66e1738dc0ce9eb
